language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.3
  - rbx-2.2.10
before_install:
  - sudo apt-get install imagemagick libmagickcore-dev libmagickwand-dev
  - sudo apt-get install -qq graphicsmagick
