language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - rbx
  - jruby
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - sudo apt-get update
  - sudo apt-get install imagemagick libmagickcore-dev libmagickwand-dev
  - sudo apt-get install -qq graphicsmagick
  - gem update bundler
